### ISSUE TITLE
Fatal Error: undefined method `on' for nil:NilClass

### ISSUE THREAD

**Issue by Intelligent2013** [relaton/relaton-iev#19]
Source issue: https://github.com/metanorma/mnconvert/issues/380

From https://github.com/metanorma/mnconvert/actions/runs/4318386602/jobs/7536617942:
```
cd tests/iso-8601-1 && metanorma site generate --agree-to-terms
[info]: Compiling /home/runner/work/mnconvert/mnconvert/tests/iso-8601-1/sources/iso-tc154-8601-1-en.adoc ...
[relaton] International Astronomical Union Resolution B1.9 (2000) does not have a recognised prefix
[relaton-iso] ("ISO/IEC 646") Fetching from ISO...
[relaton-bipm] ("BIPM Recommendation CCTF 3 (2017)") fetching...
[relaton-itu] ("ITU-R TF.460-6") fetching...
[relaton-iso] ("ISO 8601-2:2019") Fetching from ISO...
[relaton-itu] ("ITU-R TF.460-6") found ITU-R TF.460-6
[relaton-bipm] ("BIPM Recommendation CCTF 3 (2017)") not found.
[relaton-iso] ("ISO 8601-2:2019") Found exact match.
[relaton-iso] ("ISO/IEC 646") Found ("ISO/IEC 646:1991").
[relaton] International Astronomical Union Resolution B1.9 (2000) does not have a recognised prefix
[relaton-iec] ("IEC 60050-113") fetching...
[relaton-iec] ("IEC 60050-113") found IEC 60050-113:2011
Fatal Error: undefined method `on' for nil:NilClass
/opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-iev-1.1.5/lib/relaton_iev.rb:56:in `refs_iev2iec60050part1': undefined method `on' for nil:NilClass (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-iev-1.1.5/lib/relaton_iev.rb:46:in `block in refs_iev2iec60050part'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-iev-1.1.5/lib/relaton_iev.rb:44:in `each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-iev-1.1.5/lib/relaton_iev.rb:44:in `refs_iev2iec60050part'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-iev-1.1.5/lib/relaton_iev.rb:76:in `iev_cleanup'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.3.9/lib/metanorma/standoc/cleanup.rb:56:in `cleanup'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.3.9/lib/metanorma/standoc/base.rb:196:in `makexml'
```

How to repeat locally:
```
git clone https://github.com/metanorma/iso-8601-1
cd iso-8601-1
bundle update
cd sources
bundle exec metanorma -t iso -x presentation iso-tc154-8601-1-en.adoc
```

**Comment by ronaldtse** [comment]
@andrew2net can you have a look at this? Thanks!

**Comment by andrew2net** [comment]
@Intelligent2013 It was an issue with the new IEC data source we stared using recently. I fixed the dataset and it works for me. Please try it again and feel free to close the issue if everything is ok.

**Comment by Intelligent2013** [comment]
Confirmed.
@andrew2net thank you!
